INSERT INTO CUSTOMER_USER_COMPANY (COMPANY_ID, PERSONNEL_ID, STATUS, ADMIN_ROLE)
VALUES ('COMP001', 1001, 'A', 'ADMIN');
INSERT INTO CUSTOMER_USER_COMPANY (COMPANY_ID, PERSONNEL_ID, STATUS, ADMIN_ROLE)
VALUES ('COMP002', 1001, 'A', 'USER');
INSERT INTO CUSTOMER_USER_COMPANY (COMPANY_ID, PERSONNEL_ID, STATUS, ADMIN_ROLE)
VALUES ('COMP001', 1002, 'A', 'USER');

INSERT INTO CUSTOMER_COMPANY_PAGE (COMPANY_ID, PAGE_ID)
VALUES ('COMP001', 'PAGE001');
INSERT INTO CUSTOMER_COMPANY_PAGE (COMPANY_ID, PAGE_ID)
VALUES ('COMP001', 'PAGE002');
INSERT INTO CUSTOMER_COMPANY_PAGE (COMPANY_ID, PAGE_ID)
VALUES ('COMP002', 'PAGE001');

INSERT INTO CUSTOMER_USER_PAGE (COMPANY_ID, PERSONNEL_ID, PAGE_ID, ADMIN_ROLE)
VALUES ('COMP001', 1001, 'PAGE001', 'EDITOR');
INSERT INTO CUSTOMER_USER_PAGE (COMPANY_ID, PERSONNEL_ID, PAGE_ID, ADMIN_ROLE)
VALUES ('COMP001', 1001, 'PAGE002', 'VIEWER');
INSERT INTO CUSTOMER_USER_PAGE (COMPANY_ID, PERSONNEL_ID, PAGE_ID, ADMIN_ROLE)
VALUES ('COMP002', 1001, 'PAGE001', 'EDITOR');
