CREATE TABLE CUSTOMER_USER_COMPANY (
    COMPANY_ID VARCHAR(30) NOT NULL,
    PERSONNEL_ID NUMBER(19) NOT NULL,
    STATUS VARCHAR(1),
    DEFAULT_FACILITY_ID VARCHAR(30),
    DEFAULT_HUB VARCHAR(12),
    ADMIN_ROLE VARCHAR(12),
    DATA_SOURCE VARCHAR(30),
    LOCKOUT_DATE DATE,
    DEFAULT_OPS_ENTITY_ID VARCHAR(30),
    ITAR_ROLE VARCHAR(12),
    MSDS_OC_ROLE CHAR(1),
    USER_PREFERENCE_DATA CLOB,
    PRIMARY KEY (COMPANY_ID, PERSONNEL_ID)
);

CREATE TABLE CUSTOMER_COMPANY_PAGE (
    COMPANY_ID VARCHAR(30) NOT NULL,
    PAGE_ID VARCHAR(30) NOT NULL,
    PRIMARY KEY (COMPANY_ID, PAGE_ID)
);

CREATE TABLE CUSTOMER_USER_PAGE (
    COMPANY_ID VARCHAR(30) NOT NULL,
    PERSONNEL_ID NUMBER(19) NOT NULL,
    PAGE_ID VARCHAR(30) NOT NULL,
    ADMIN_ROLE VARCHAR(12),
    PRIMARY KEY (COMPANY_ID, PERSONNEL_ID, PAGE_ID),
    FOREIGN KEY (COMPANY_ID, PAGE_ID) REFERENCES CUSTOMER_COMPANY_PAGE(COMPANY_ID, PAGE_ID),
    FOREIGN KEY (COMPANY_ID, PERSONNEL_ID) REFERENCES CUSTOMER_USER_COMPANY(COMPANY_ID, PERSONNEL_ID)
);
